apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: john9101/post-service:0.0.1
          imagePullPolicy: Never

